config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end

root to: 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :delete_all
  belongs_to :user
  validates :name, presence: :true, uniqueness: { scope: :user_id , length: { maximum: 50 } }

  def percent_complete
    return 0 if total_tasks == 0
    ( 100 * completed_tasks.to_f / total_tasks ).round
  end

  def completed_tasks
    @completed_tasks ||= tasks.completed.count
  end

  def total_tasks
    @total_tasks ||= tasks.count
  end

  def progress
    case percent_complete.to_i
    when 0
      'Not started'
    when 100
      'Complete'
    else
      'In progress'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'info'
    else
      'primary'
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: :true, uniqueness: { scope: :project_id, length: { maximum: 150 } }

  scope :completed, -> do
    where(status: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, -> { includes(:tasks) }, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
    @task = Task.new
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id if current_user

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = @project.tasks.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = @project.tasks.new(task_params)
    project_id = set_project.id

    if @task.save
      redirect_to(@project)
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(task_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to @project, notice: 'Task was successfully destroyed.'
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:name, :status, :completed_at, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def copyright_generator
    OlindosViewTool::Renderer.copyright 'Yaroslav Mohutin', 'All rights reserved'
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page" id="page">
      <% if current_user %>
        <div class="head">
          You are logged in as
          <%= current_user.email %>
          |
          <%= link_to 'logout', destroy_user_session_path, method: :delete %>
        </div>
      <% end %>
      <div class="page-title">
        SIMPLE TODO LIST
        <div class="sub">
          FROM RUBY GARAGE
        </div>
      </div>
    </div>

    <p id="notice"><%= notice %></p>
    <%= yield %>

    <div class="mastfoot">
     <p class="app-footer"><%= copyright_generator %></p>
    </div>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
      <div class="card mt-5">
        <div class="card-header">
          <div class="row">
            <div class="col-1">
              <%= link_to fa_icon('angle-left'), projects_path, class: 'btn btn-dark' %>
            </div>
            <div class="col-11">
              <%= simple_form_for(@project) do |f| %>
                <div class="input-group mb-4">
                  <%= f.text_field :name, class: 'form-control' %>
                  <div class="input-group-append">
                    <%= f.submit 'Update', class: 'btn btn-primary input-group-btn' %>
                  </div>
                </div>
              <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
      <div class="card mt-5">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h4>
            <b>My Todo Lists</b>
          </h4>
          <%= link_to 'Add TODO list', new_project_path, class: "btn btn-primary btm-sm" %>
        </div>

        <div class="card-body">
          <ul class="list-group">
            <% @projects.each do |project| %>
              <%= link_to project, class: 'text-decoration-none' do %>
                <li class="list-group-item d-flex justify-content-between">
                  <div>
                    <h5 class='m-0 text-dark'>
                      <b><%= project.name %></b>
                      <span class="badge badge-<%= project.badge_color %>"><%= project.progress %></span>
                    </h5>
                    <p class="text-secondary m-0"><small><%= project.percent_complete %>% Complete ( <%= project.completed_tasks %>/<%= project.total_tasks %> Tasks )</small>
                    </p>
                  </div>
                  <div class="row">
                    <div class="col-11">
                      <%= link_to fa_icon('pencil'), edit_project_path(project) %>
                      <%= link_to fa_icon('trash'), project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
      <div class="card mt-5">
        <div class="card-header">
          <div class="row">
            <div class="col-1">
              <%= link_to fa_icon('angle-left'), projects_path, class: 'btn btn-dark' %>
            </div>
            <div class="col-11">
              <%= simple_form_for(@project) do |f| %>
                <div class="input-group mb-4">
                  <%= f.text_field :name, class: 'form-control', placeholder: "Add a new project" %>
                  <div class="input-group-append">
                    <%= f.submit 'Add', class: 'btn btn-primary input-group-btn' %>
                  </div>
                </div>
              <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
      <div class="card mt-5">
        <div class="card-header">
          <div class="row">
            <div class="col-1">
              <%= link_to fa_icon('angle-left'), projects_path, class: 'btn btn-dark' %>
            </div>
            <div class="col-11">
              <div class="d-flex justify-content-between">
                <div>
                  <h5 class="m-0">
                    <b><%= @project.name %></b>
                    <span class="badge badge-<%= @project.badge_color %>"><%= @project.progress %></span>
                  </h5>
                  <p class="text-secondary m-0"><small><%= @project.percent_complete %>% Complete ( <%= @project.completed_tasks %>/<%= @project.total_tasks %> Tasks )</small></p>
                </div>
                <div class="col-1">
                  <%= link_to fa_icon('pencil'), edit_project_path(@project), class: 'btn btn-dark' %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="progress mb-4">
            <div class="progress-bar bg-info" role="progressbar" style="width: <%= @project.percent_complete %>%" aria-valuenow="<%= @project.percent_complete %>" aria-valuemin="0" aria-valuemax="100"></div>
          </div>

          <%= simple_form_for([@project, @task]) do |f| %>
            <div class="input-group mb-4">
              <%= f.text_field :name, class: 'form-control', placeholder: "Add a new task" %>
              <div class="input-group-append">
                <%= f.submit 'Add', class: 'btn btn-primary input-group-btn' %>
              </div>
            </div>
          <% end %>

          <ul class="list-group">
            <% @project.tasks.each do |task| %>
              <% if task.status? %>
                <div class="row">
                  <div class="col-11">
                    <li class='list-group-item bg-light'>
                      <%= link_to '', class: "btn btn-dark", data: { reflex: 'click->ExampleReflex#mark_incomplete', id: task.id } do %>
                        <i class="fa fa-undo"></i>
                      <% end %>
                      <span class="text-muted">
                        <em><%= task.name %></em>
                      </span>
                    </li>
                  </div>
                  <div class="col-1">
                    <%= link_to fa_icon('pencil'), edit_project_task_path(task.project_id, task.id) %>
                    <%= link_to fa_icon('trash'), project_task_path(task.project_id, task.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                </div>
                <% else %>
                <div class="row">
                  <div class="col-11">
                    <li class='list-group-item'>
                      <%= link_to '', class: "btn btn-info", data: { reflex: 'click->ExampleReflex#mark_complete', id: task.id } do %>
                        <i class="fa fa-check"></i>
                      <% end %>
                      <%= task.name %>
                    </li>
                  </div>
                  <div class="col-1">
                    <%= link_to fa_icon('pencil'), edit_project_task_path(task.project_id, task.id) %>
                    <%= link_to fa_icon('trash'), project_task_path(task.project_id, task.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
      <div class="card mt-5">
        <div class="card-header">
          <div class="row">
            <div class="col-sm-12">
              <%= simple_form_for([@project, @task]) do |f| %>
                <%= f.input :name, class: 'form-control' %>
                <%= f.input :status, as: :boolean, checked_value: true, unchecked_value: false %>
                <div class="input-group date">
                  <%= f.input :completed_at, as: :date, order: [:day, :month, :year] %>
                </div>
                <%= f.submit 'Update', class: 'btn btn-primary input-group-btn' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>